recipebook/ledger/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("recipes/list/", views.basicParams, name="basicParams"),
    path("recipe/<int:num>/", views.tasks, name="tasks"),
    path("recipe/add/", views.add_recipe, name="add_recipe"),
    path("recipe/<int:pk>/add_image", views.add_image, name="add_image"),
]

app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("ledger.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/ledger/models.py
from django.db import models
from django.contrib.auth.models import User

class Ingredient(models.Model):
    name = models.CharField(max_length=50)

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=1)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=50)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name="recipe")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients")

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=255)
    year_level = models.IntegerField()
    course = models.CharField(max_length=10)

class RecipeImage(models.Model):
    image = models.ImageField(upload_to='recipe_images/')
    description = models.CharField(max_length=255)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="images")

recipebook/ledger/forms.py
from django import forms
from .models import Recipe, RecipeIngredient, Ingredient, RecipeImage

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'

class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = '__all__'

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = '__all__'

recipebook/ledger/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Recipe, RecipeIngredient, Ingredient, RecipeImage
from .forms import RecipeForm, RecipeIngredientForm, IngredientForm, RecipeImageForm
from django.forms import modelformset_factory

@login_required
def basicParams(request):
    # recipe list
    recipes = Recipe.objects.all()
    return render(request, 'basicParams.html', {'recipes': recipes})

@login_required
def tasks(request, num):
    # recipe task
    recipe = Recipe.objects.get(id=num)
    return render(request, 'task_list.html', {'recipe':recipe})

@login_required
def add_recipe(request):
    # handle multiple forms at once (RecipeForm, RecipeIngredienForm, IngredientForm)
    RecipeIngredientFormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=3)

    if request.method == "POST":

        if 'add_recipe' in request.POST:
            form = RecipeForm(request.POST)
            if form.is_valid():
                recipe = form.save(commit=False)
                recipe.author = request.user
                recipe.save()
                return redirect('ledger:tasks', num=recipe.id)

        elif 'add_ingredient' in request.POST:
            ingredient_form = IngredientForm(request.POST)
            if ingredient_form.is_valid():
                ingredient_form.save()
                return redirect('ledger:add_recipe')
                
        elif 'add_recipe_ingredient' in request.POST:
            formset = RecipeIngredientFormSet(request.POST)
            if formset.is_valid():
                for recipe_ingredient_form in formset:
                    if recipe_ingredient_form.cleaned_data:
                        # check each ingredient and selected recipe, then link and save
                        ingredient = recipe_ingredient_form.save(commit=False)
                        selected_recipe = recipe_ingredient_form.cleaned_data.get('recipe')
                        if selected_recipe:
                            ingredient.recipe = selected_recipe
                        ingredient.save()
                return redirect('ledger:tasks', num=selected_recipe.id)
        
    else:
        form = RecipeForm()
        formset = RecipeIngredientFormSet(queryset=RecipeIngredient.objects.none())
        ingredient_form = IngredientForm()

    recipes = Recipe.objects.all()

    return render(request, 'add_recipe.html', {
        'form': form, 
        'formset': formset, 
        'ingredient_form': ingredient_form,
        'recipes': recipes,
    })

@login_required
def add_image(request, pk):
    recipe = Recipe.objects.get(id=pk)
    if request.method == 'POST':
        form = RecipeImageForm(request.POST, request.FILES)
        if form.is_valid():
            recipe_image = form.save(commit=False)
            recipe_image.recipe = recipe
            recipe_image.save()
            return redirect('ledger:tasks', num=pk)
    else:
        form = RecipeImageForm()

    return render(request, 'add_image.html', {'form': form, 'recipe': recipe})

recipebook/ledger/templates/add_image.html
{% extends 'baseTemplate.html' %}
{% block page_title %}Upload Image for {{ recipe.name }}{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

recipebook/ledger/templates/add_recipe.html
{% extends 'baseTemplate.html' %}
{% block page_title %}Add a Recipe{% endblock %}
{% block content %}
    <h4>All Recipes:</h4>
    <ul>
        {% for recipe in recipes %}
            <li>Recipe Name: {{ recipe.name }}</li>
        {% endfor %}
    </ul>

    <h4>Add New Recipe</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="add_recipe">Submit</button>
    </form>

    <h4>Add Recipe Ingredients</h4>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for f in formset %}
            {{ f.as_p }}
        {% endfor %}
        <button type="submit" name="add_recipe_ingredient">Submit</button>
    </form>

    <h4>Add New Ingredient</h4>
    <form method="post">
        {% csrf_token %}
        {{ ingredient_form.as_p }}
        <button type="submit" name="add_ingredient">Submit</button>
    </form>
{% endblock %}

recipebook/ledger/templates/baseTemplate.html
<!DOCTYPE html>
<html lang="en-US">
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

	<title>Recipe Book</title>
</head>
<body>
	<nav class="navbar navbar-expand navbar-dark bg-dark">
		<div class="container-fluid">
			<div>
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'ledger:basicParams' %}">Recipe Book</a>
					</li>
				</ul>
			</div>
			<div>
				<ul class="navbar-nav">
					<li class="nav-item">
						{% if user.is_authenticated %}
						    <form method="post" action="{% url 'logout' %}">
						        {% csrf_token %}
						        <button class="nav-link" type="submit">Logout</button>
						    </form>
						{% else %}
						    <a class="nav-link" href="{% url 'login' %}">Login</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<div id="container">
		<h1>{% block page_title %}{% endblock %}</h1>
	</div>
	<div id="content">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

recipebook/ledger/templates/basicParams.html
{% extends 'baseTemplate.html' %}
{% block page_title %}Recipe List{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'ledger:add_recipe' %}">Create New Recipe</a>
        <ul>
            {% for recipe in recipes %}
                <li>
                    <a href="{% url 'ledger:tasks' recipe.id %}">{{ recipe.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

recipebook/ledger/templates/task_list.html
{% extends 'baseTemplate.html' %}
{% block page_title %}Recipe Details{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h2>Name: {{ recipe.name }}</h2>
        <h4>Author: {{ recipe.author.profile.name }}</h3>
        <h5>Created On: {{ recipe.created_on }}</h3>
        <h5>Updated On: {{ recipe.updated_on }}</h3>
        <h3>Ingredients:</h3>
        <ul>
            {% for ingredient in recipe.ingredients.all %}
                <li>{{ ingredient.quantity }} {{ ingredient.ingredient.name }}</li>
            {% endfor %}
        </ul>
        <h3>Images:</h3>
        <ul>
            {% for img in recipe.images.all %}
                <li>
                    <img src="{{ img.image.url }}" alt="{{ img.description }}"/>
                    <p>{{ img.description }}</p>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'ledger:add_image' recipe.id %}">Upload New Image</a>
    {% endif %}
{% endblock %}